#!/usr/bin/env zsh
#compdef abstouch

_abstouch()
{
    _arguments -C \
        "1: :(help start stop setup calibrate config)" \
        "*::arg:->args"

    case $line[1] in
        start)
            _abstouch_start
        ;;
        calibrate)
            _abstouch_calibrate
        ;;
    esac
}

_abstouch_start()
{
    _arguments \
        '--foreground[Runs the client on foreground instead of background.]' \
        '--quiet[Disables the output with the client except errors.]'
}

_abstouch_calibrate()
{
    _arguments \
        '--no-visual[Disables the visualization while calibrating.]'
}

compdef _abstouch abstouch
